drop table if exists matching_criteria;
drop table if exists vuln_reference;
drop table if exists vuln_rating;
drop table if exists vuln_alias;
drop table if exists vuln_related;
drop table if exists vuln_data;
drop table if exists vuln;
drop table if exists source_metadata;
drop table if exists source;