name: Enhancement Request
description: File an enhancement request
labels: [ "enhancement" ]
body:
- type: textarea
  id: behavior-current
  attributes:
    label: Current Behavior
    description: |-
      Describe the current behavior that you observed.
      Consider providing screenshots, log output, and other supplementary data.
      
      *Files and images can be included via drag and drop into this text field.*
  validations:
    required: true
- type: textarea
  id: behavior-proposed
  attributes:
    label: Proposed Behavior
    description: >-
      Describe how you expect Dependency-Track to behave instead.
      Please include *why* you want the new behavior.
  validations:
    required: true
